# Generated by Django 5.1.4 on 2025-01-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0004_remove_coursecontent_video_url_comment_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='scheduled_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Mulai'),
        ),
    ]
