# Generated by Django 5.1.4 on 2025-01-06 00:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_coursecontent_scheduled_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together={('course_id', 'user_id')},
        ),
    ]
