# Generated by Django 5.1.4 on 2025-01-06 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0006_alter_coursemember_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'verbose_name': 'Konten Mata Kuliah', 'verbose_name_plural': 'Konten Mata Kuliah'},
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lms_core.course', verbose_name='Mata Kuliah'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Lampiran File'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Konten'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='lms_core.coursecontent', verbose_name='Induk Konten'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
    ]
