# Generated by Django 5.1.4 on 2025-01-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0009_alter_announcement_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
    ]
